//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segundo_A
    {
        public int NUM_LISTA { get; set; }
        public int MATRICULA { get; set; }
        public string NOMBRE { get; set; }
        public int CAL1 { get; set; }
        public int CAL2 { get; set; }
        public int CAL3 { get; set; }
        public int CAL4 { get; set; }
        public int CAL5 { get; set; }
        public int CAL6 { get; set; }
        public int PROMEDIO { get; set; }
        public string CORREO { get; set; }
        public string NOTAS { get; set; }
    }
}
